baseurl = "https://manuvanderveeren.netlify.app"
title = "HOME"

theme = "hugo-coder-portfolio"

DefaultContentLanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Manu Vanderveeren"
    description = "Manu Vanderveeren's personal website"
    keywords = "blog,developer,personal"
    info = "London Business School MFA 2021 Student"
    avatarurl = "images/avatar.jpg"
    fixedbarContent = "Do you want to contact me via e-mail?→"
    fixedbarContentAfter = "manuv.mfa2021@london.edu | Please share my profile if you like it→"

    hideCredits = false
    hideCopyright = false

    # Bottom sns share
    snsShare = true
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = true
    enableFacebookShare = true
    enableLinkedInShare = true

    thumbnail = "images/tn.png"

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = "|"


[[params.social]]
    name = "LinkedIn"
    weight = 4
    url = "https://www.linkedin.com/in/manuvanderveeren/"



        [menu] # It is possible to change the menu too.

            [[menu.main]]
                name = "About"
                weight = 1.0
                url = "about"

            [[menu.main]]
                name = "Projects"
                weight = 2
                url = "projects"

